apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata: 
  labels:
    app: redis
    role: master
  name: redis-master
  namespace: global
spec: 
    replicas: 1
    selector: 
        app: redis
        role: master
    template: 
        metadata: 
            labels: 
                app: redis
                role: master
        spec: 
            containers: 
            - name: redis-master
              image: redis:2.8.23
            ports: 
            - name: redis-server
              containerPort: 6379
    placement:
      clusters:
      - name: cluster-federation-aws
      - name: cluster-federation-azure
      - name: cluster-federation-gcp
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata: 
    name: redis-master
    namespace: global
    labels: 
        app: redis
        role: master
spec: 
    ports: 
        - port: 6379
          targetPort: redis-server
    selector: 
        app: redis
        role: master
    placement:
      clusters:
      - name: cluster-federation-aws
      - name: cluster-federation-azure
      - name: cluster-federation-gcp
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata: 
  labels:
    app: redis
    role: slave
  name: redis-slave
  namespace: global
  namespace: default
spec: 
    replicas: 1
    selector: 
        app: redis
        role: slave
    template: 
        metadata: 
            labels: 
                app: redis
                role: slave
        spec: 
            containers: 
            - name: redis-slave
              image: redis:2.8.23
            ports: 
            - name: redis-server
              containerPort: 6379
    placement:
      clusters:
      - name: cluster-federation-aws
      - name: cluster-federation-azure
      - name: cluster-federation-gcp
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata: 
    name: redis-slave
    namespace: global
    labels: 
        app: redis
        role: slave
spec: 
    ports: 
        - port: 6379
          targetPort: redis-server
    selector: 
        app: redis
        role: slave
    placement:
      clusters:
      - name: cluster-federation-aws
      - name: cluster-federation-azure
      - name: cluster-federation-gcp
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata: 
    name: guestbook
    namespace: global
    labels: 
        app: guestbook
spec: 
 replicas: 3
 selector: 
    app: guestbook
 template: 
  metadata: 
   labels: 
    app: guestbook
  spec: 
    containers: 
      - name: guestbook
        image: k8s.gcr.io/guestbook:v3
    ports: 
      - name: http-server
        containerPort: 3000
    placement:
      clusters:
      - name: cluster-federation-aws
      - name: cluster-federation-azure
      - name: cluster-federation-gcp
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata: 
    name: guestbook
    namespace: global
    labels: 
        app: guestbook
spec: 
    ports: 
        - port: 3000
          targetPort: http-server
    selector: 
        app: guestbook
        type: LoadBalancer
    placement:
      clusters:
      - name: cluster-federation-aws
      - name: cluster-federation-azure
      - name: cluster-federation-gcp