apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOnsidXNlcm5hbWUiOiJncmVnb3YiLCJwYXNzd29yZCI6IjdlNTZkNDk3YWFhYWQ3OWFkMWUzY2I2MWQyMjY1YmEzYWE0OTM3YzAiLCJlbWFpbCI6ImdyZWdvaXJlLnJlYm91bEBnbWFpbC5jb20iLCJhdXRoIjoiWjNKbFoyOTJPamRsTlRaa05EazNZV0ZoWVdRM09XRmtNV1V6WTJJMk1XUXlNalkxWW1FellXRTBPVE0zWXpBPSJ9fX0=
type: kubernetes.io/dockerconfigjson
