apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  labels:
    app: redis
    role: master
  name: redis-master
  namespace: global
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: redis
          role: master
      template:
        metadata:
          labels:
            app: redis
            role: master
        spec:
          containers:
          - image: redis:2.8.23
            name: redis-master
            ports:
            - containerPort: 6379
              name: redis-server


---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata:
  labels:
    app: redis
    role: master
  name: redis-master
  namespace: global
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      ports:
      - port: 6379
        targetPort: redis-server
      selector:
        app: redis
        role: master


---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  labels:
    app: redis
    role: slave
  name: redis-slave
  namespace: global
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: redis
          role: slave
      template:
        metadata:
          labels:
            app: redis
            role: slave
        spec:
          containers:
          - image: k8s.gcr.io/redis-slave:v2
            name: redis-slave
            ports:
            - containerPort: 6379
              name: redis-server
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata:
  labels:
    app: redis
    role: slave
  name: redis-slave
  namespace: global
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      ports:
      - port: 6379
        targetPort: redis-server
      selector:
        app: redis
        role: slave


---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  labels:
    app: guestbook
    version: "1"
  name: guestbook
  namespace: global
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  template:
    metadata:
      labels:
        app: guestbook
        version: "1"
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: guestbook
          version: "1"
      template:
        metadata:
          labels:
            app: guestbook
            version: "1"
        spec:
          imagePullSecrets:
          - name: regcred
          containers:
          - image: docker.pkg.github.com/gregov/arctiq-ext-mission/guestbook-go:1
            name: guestbook
            ports:
            - containerPort: 3000
              name: http-server


---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata:
  labels:
    app: guestbook
  name: guestbook
  namespace: global
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  template:
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: guestbook.global.earlyfrench.ca
        external-dns.alpha.kubernetes.io/ttl: "60"
      labels:
        app: guestbook
    spec:
      ports:
      - port: 80
        targetPort: http-server
      selector:
        app: guestbook
        version: "1"
      type: LoadBalancer
  overrides:
    - clusterName: cluster-federation-aws
      clusterOverrides:
        - path: "/metadata/annotations"
          op: "add"
          value:
            external-dns.alpha.kubernetes.io/hostname: aws-guestbook.global.earlyfrench.ca
            external-dns.alpha.kubernetes.io/ttl: "60"
    - clusterName: cluster-federation-azure
      clusterOverrides:
        - path: "/metadata/annotations"
          op: "add"
          value:
            external-dns.alpha.kubernetes.io/hostname: azure-guestbook.global.earlyfrench.ca
            external-dns.alpha.kubernetes.io/ttl: "60"
    - clusterName: cluster-federation-gcp
      clusterOverrides:
        - path: "/metadata/annotations"
          op: "add"
          value:
            external-dns.alpha.kubernetes.io/hostname: gcp-guestbook.global.earlyfrench.ca
            external-dns.alpha.kubernetes.io/ttl: "60"
