{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "deploy.serviceAccountName" . }}
  labels:
{{ include "deploy.labels" . | indent 4 }}
{{- end -}}
