apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  labels:
    app: redis
    role: master
  name: redis-master
  namespace: default
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  replicas: 1
  selector:
    app: redis
    role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - image: redis:2.8.23
        name: redis-master
        ports:
        - containerPort: 6379
          name: redis-server


---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata:
  labels:
    app: redis
    role: master
  name: redis-master
  namespace: global
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: master


---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  labels:
    app: redis
    role: slave
  name: redis-slave
  namespace: default
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  replicas: 2
  selector:
    app: redis
    role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - image: redis:2.8.23
        name: redis-slave
        ports:
        - containerPort: 6379
          name: redis-server


---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata:
  labels:
    app: redis
    role: slave
  name: redis-slave
  namespace: global
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: slave


---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  labels:
    app: guestbook
  name: guestbook
  namespace: global
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  replicas: 3
  selector:
    app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: k8s.gcr.io/guestbook:v3
        name: guestbook
        ports:
        - containerPort: 3000
          name: http-server


---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata:
  labels:
    app: guestbook
  name: guestbook
  namespace: global
spec:
  placement:
    clusters:
    - name: cluster-federation-aws
    - name: cluster-federation-azure
    - name: cluster-federation-gcp
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer
