---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: mongodb        
  name: my-rocketchat-mongodb-arbiter
spec:
  selector:
    matchLabels:
      app: mongodb      
      component: arbiter
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: mongodb        
  name: my-rocketchat-mongodb-secondary
spec:
  selector:
    matchLabels:
      app: mongodb      
      component: secondary
---
apiVersion: v1
kind: Secret
metadata:
  name: my-rocketchat-mongodb
  labels:
    app: mongodb        
type: Opaque
data:
  mongodb-root-password:  "cm9vdC1jaGFuZ2VtZQ=="
  mongodb-password:  "Y2hhbmdlbWU="
  mongodb-replica-set-key: "ZjBXV3ZWVkswMQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: my-rocketchat-rocketchat
  labels:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: my-rocketchat
type: Opaque
data:
  mongo-uri: "bW9uZ29kYjovL3JvY2tldGNoYXQ6Y2hhbmdlbWVAbXktcm9ja2V0Y2hhdC1tb25nb2RiOjI3MDE3L3JvY2tldGNoYXQ="
  mongo-oplog-uri: "bW9uZ29kYjovL3Jvb3Q6cm9vdC1jaGFuZ2VtZUBteS1yb2NrZXRjaGF0LW1vbmdvZGI6MjcwMTcvbG9jYWw/cmVwbGljYVNldD1yczAmYXV0aFNvdXJjZT1hZG1pbg=="
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: my-rocketchat
  name: my-rocketchat-rocketchat
---
apiVersion: v1
kind: Service
metadata:
  name: my-rocketchat-mongodb-headless
  labels:
    app: mongodb        
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
  selector:
    app: mongodb    
---
apiVersion: v1
kind: Service
metadata:
  name: my-rocketchat-mongodb
  labels:
    app: mongodb        
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: mongodb    
    component: primary
---
apiVersion: v1
kind: Service
metadata:
  name: my-rocketchat-rocketchat
  labels:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: my-rocketchat
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rocketchat.global.earlyfrench.ca
    external-dns.alpha.kubernetes.io/ttl: "600"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: my-rocketchat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rocketchat-rocketchat
  labels:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: my-rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rocketchat
      app.kubernetes.io/instance: my-rocketchat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rocketchat
        app.kubernetes.io/instance: my-rocketchat
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
      containers:
      - name: rocketchat
        image: "docker.io/rocketchat/rocket.chat:2.4.9"
        imagePullPolicy: IfNotPresent
        env:
        - name: DEPLOY_PLATFORM
          value: helm-chart
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: my-rocketchat-rocketchat
              key: mongo-uri
        - name: MONGO_OPLOG_URL
          valueFrom:
            secretKeyRef:
              name: my-rocketchat-rocketchat
              key: mongo-oplog-uri
        ports:
        - name: http
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/info
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/info
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          null
          
        volumeMounts:
        - name: rocket-data
          mountPath: /app/uploads
      volumes:
      - name: rocket-data
        emptyDir: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb        
  name: my-rocketchat-mongodb-arbiter
spec:
  selector:
    matchLabels:
      app: mongodb      
      component: arbiter
  serviceName: my-rocketchat-mongodb-headless
  replicas: 0
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb                
        component: arbiter
    spec:
      securityContext:
        fsGroup: 1001      
      containers:
        - name: mongodb-arbiter
          image: docker.io/bitnami/mongodb:4.0.12-debian-9-r5
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
          - containerPort: 27017
            name: mongodb
          env:
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGODB_REPLICA_SET_MODE
            value: "arbiter"
          - name: MONGODB_PRIMARY_HOST
            value: my-rocketchat-mongodb
          - name: MONGODB_REPLICA_SET_NAME
            value: "rs0"
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: "$(MONGODB_POD_NAME).my-rocketchat-mongodb-headless.default.svc.cluster.local"
          - name: MONGODB_PRIMARY_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-rocketchat-mongodb
                key: mongodb-root-password
          - name: MONGODB_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: my-rocketchat-mongodb
                key: mongodb-replica-set-key
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          livenessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
          resources:
            {}
            
      volumes:
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb        
  name: my-rocketchat-mongodb-primary
spec:
  serviceName: my-rocketchat-mongodb-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mongodb      
      component: primary
  template:
    metadata:
      labels:
        app: mongodb                
        component: primary
    spec:
      securityContext:
        fsGroup: 1001      
      initContainers:
      containers:
        - name: mongodb-primary
          image: docker.io/bitnami/mongodb:4.0.12-debian-9-r5
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
          - containerPort: 27017
            name: mongodb
          env:
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGODB_REPLICA_SET_MODE
            value: "primary"
          - name: MONGODB_REPLICA_SET_NAME
            value: "rs0"
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: "$(MONGODB_POD_NAME).my-rocketchat-mongodb-headless.default.svc.cluster.local"
          - name: MONGODB_USERNAME
            value: "rocketchat"
          - name: MONGODB_DATABASE
            value: "rocketchat"
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-rocketchat-mongodb
                key: mongodb-password
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-rocketchat-mongodb
                key: mongodb-root-password
          - name: MONGODB_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: my-rocketchat-mongodb
                key: mongodb-replica-set-key
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: datadir
              mountPath: /bitnami/mongodb
              subPath: 
          resources:
            {}
      volumes:
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb        
  name: my-rocketchat-mongodb-secondary
spec:
  selector:
    matchLabels:
      app: mongodb      
      component: secondary
  podManagementPolicy: "Parallel"
  serviceName: my-rocketchat-mongodb-headless
  replicas: 0
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb                
        component: secondary
    spec:
      securityContext:
        fsGroup: 1001      
      initContainers:
      containers:
        - name: mongodb-secondary
          image: docker.io/bitnami/mongodb:4.0.12-debian-9-r5
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
          - containerPort: 27017
            name: mongodb
          env:
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGODB_REPLICA_SET_MODE
            value: "secondary"
          - name: MONGODB_PRIMARY_HOST
            value: my-rocketchat-mongodb
          - name: MONGODB_REPLICA_SET_NAME
            value: "rs0"
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: "$(MONGODB_POD_NAME).my-rocketchat-mongodb-headless.default.svc.cluster.local"
          - name: MONGODB_PRIMARY_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-rocketchat-mongodb
                key: mongodb-root-password
          - name: MONGODB_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: my-rocketchat-mongodb
                key: mongodb-replica-set-key
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: datadir
              mountPath: /bitnami/mongodb
              subPath: 
          resources:
            {}
            
      volumes:
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
