name: Docker Image CI

on: 
  push:
    paths:
    - 'guestbook-go/src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd guestbook-go/src
        docker build -t docker.pkg.github.com/gregov/arctiq-ext-mission/guestbook-go:$GITHUB_RUN_NUMBER .
    - name: Authenticate to the registry and push the container
      run:  |
        docker login docker.pkg.github.com -u ${{ github.actor }} -p "${{ secrets.GITHUB_TOKEN }}"
        docker push docker.pkg.github.com/gregov/arctiq-ext-mission/guestbook-go:$GITHUB_RUN_NUMBER
